version: '3.5'

services:
  microservice_template:
    image: microservice_template:latest
    container_name: microservice_template
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - JHIPSTER_SLEEP=30
      - SPRING_APPLICATION_NAME=microservice_template
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_CLOUD_CONFIG_ENV=dev
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_CLOUD_CONFIG_LABEL=master
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - EUREKA_INSTANCE_PORT=8086      
    ports:
      - 8086:8086

  microservice_template2:
    image: microservice_template:latest
    container_name: microservice_template2
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - JHIPSTER_SLEEP=30
      - SPRING_APPLICATION_NAME=microservice_template
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_CLOUD_CONFIG_ENV=dev
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_CLOUD_CONFIG_LABEL=master
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - EUREKA_INSTANCE_PORT=8084
    ports:
      - 8084:8084

